# Generated by Django 3.2.3 on 2021-06-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='oink',
            name='body_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
