# Generated by Django 3.2.3 on 2021-06-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_oink_body_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oink',
            name='body_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
